# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

TEMPLATE = app
TARGET = SFMQTGUI
DESTDIR = ../Debug
QT += core gui
CONFIG += release
DEFINES += QT_LARGEFILE_SUPPORT QAXSERVER
INCLUDEPATH += ./GeneratedFiles \
    . \
    ./GeneratedFiles/Debug \
    ../../../libraries/pythonqt11/PythonQt-1.1/src \
    $(PYTHON_PATH)/include \
    ../../../libraries/pythonqt11/PythonQt-1.1/extensions/PythonQtGui \
    ../../../libraries/pythonqt11/PythonQt-1.1/src/gui \
    ../../Libs/voronoi/source \
    ../../../../../Research/PHD/Projects/AUSTRALIA/2012_DTD/software/qtkinect/Qkinect/QtKinectWrapper \
    ../../../../../Research/PHD/Projects/AUSTRALIA/2012_DTD/software/qtkinect/Qkinect/QtKinectWrapper/OpenNI/Include
LIBS += -lopenNI
DEPENDPATH += .
MOC_DIR += ./GeneratedFiles/debug
OBJECTS_DIR += debug
UI_DIR += ./GeneratedFiles
RCC_DIR += ./GeneratedFiles
include(SFMQTGUI.pri)
win32:RC_FILE = SFMQTGUI.rc
