#include <QtGui/QApplication>
#include <shapefactory.h>
#include <qoccdocument.h>
#include <qocccontroller.h>
#include <qoccapplication.h>
#include <QoccMainWindow.h>
//#include <ui.h>
#include <GraphWidget.h>
#include <UnitsAPI.hxx> 